export type Fair = {
  name: string;
  sector: string;
  /** "Salon professionnel" | "Congrès" | "Salon grand public" | etc. */
  type?: string;
  /** "2026" | "2027" — year only, no day/month (intentional, no maintenance needed) */
  year?: string;
  /** Optional venue if it differs from the city's main one */
  venue?: string;
};

export type CityData = {
  slug: string;
  name: string;
  region: string;
  // SEO
  title: string;
  description: string;
  // Content
  intro: string;
  hook: string;
  venues: { name: string; desc: string }[];
  /** 6–8 marquee events, displayed as a visual grid */
  featuredFairs: Fair[];
  /** Full event list — displayed in expandable table (SEO + UX) */
  allFairs: Fair[];
  sectors: string[];
  localContext: string;
  cta: string;
};

export const cities: Record<string, CityData> = {
  paris: {
    slug: "paris",
    name: "Paris",
    region: "Île-de-France",
    title:
      "Stand sur-mesure Paris, Design d'espaces & scénographie de salons | Novaus",
    description:
      "Agence de design de stands à Paris : sur-mesure, modulaires, pop-up, showrooms. Intervention sur Eurosatory, Batimat, SIAL Paris, JEC World, SIAE, Milipol, Global Industrie, VivaTech et plus de 130 salons franciliens.",
    intro:
      "Paris concentre la plus forte densité de salons professionnels d'Europe. Porte de Versailles, Paris Nord Villepinte, Le Bourget, Palais des Congrès : chaque parc accueille des événements stratégiques où votre marque se mesure à ses concurrents directs.",
    hook: "À Paris, le standard est haut. Votre stand doit l'être aussi.",
    venues: [
      {
        name: "Paris Expo Porte de Versailles",
        desc: "8 pavillons, 220 000 m². Foire de Paris, SantExpo, VivaTech, Mondial de l'Auto, EquipHotel, Salon de l'Agriculture.",
      },
      {
        name: "Paris Nord Villepinte",
        desc: "10 halls, 246 000 m². SIAL Paris, Batimat, Eurosatory, JEC World, Milipol, Maison & Objet, ALL4PACK.",
      },
      {
        name: "Paris Le Bourget",
        desc: "SIAE — Salon International de l'Aéronautique et de l'Espace, plus grand salon aéronautique mondial.",
      },
      {
        name: "Palais des Congrès de Paris",
        desc: "Congrès médicaux et scientifiques majeurs : EuroPCR, JFR, ADF, JFHOD, dermatologie, psychiatrie.",
      },
    ],
    featuredFairs: [
      { name: "Eurosatory", sector: "Défense, sécurité, aéronautique", year: "2026", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
      { name: "Batimat", sector: "Construction, bâtiment, architecture", year: "2026", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
      { name: "SIAL Paris", sector: "Agroalimentaire, food, innovation", year: "2026", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
      { name: "JEC World", sector: "Industrie, composites, matériaux", year: "2027", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
      { name: "SIAE — Salon de l'Aéronautique et de l'Espace", sector: "Aéronautique, spatial, défense", year: "2027", venue: "Paris Le Bourget", type: "Salon professionnel" },
      { name: "Milipol Paris", sector: "Sécurité intérieure, défense", year: "2027", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
      { name: "Viva Technology", sector: "Technologie, innovation, startups", year: "2026", venue: "Porte de Versailles", type: "Salon professionnel" },
      { name: "Global Industrie Paris", sector: "Industrie, machines, innovation", year: "2028", venue: "Paris Nord Villepinte", type: "Salon professionnel" },
    ],
    allFairs: [
      { name: "Foire de Paris", sector: "Habitat, consommation, lifestyle", year: "2026", type: "Salon mixte" },
      { name: "REuse Economy Expo", sector: "Environnement, économie circulaire", year: "2026", type: "Salon professionnel" },
      { name: "SantExpo", sector: "Santé, médical, médico-social", year: "2026", type: "Salon professionnel" },
      { name: "EuroPCR", sector: "Santé, cardiologie", year: "2026", type: "Congrès" },
      { name: "Biomed-J", sector: "Santé, biologie médicale", year: "2026", type: "Congrès" },
      { name: "Urgences", sector: "Santé, médecine d'urgence", year: "2026", type: "Congrès" },
      { name: "Salon de l'AMIF", sector: "Collectivités, institutionnel", year: "2026", type: "Salon professionnel" },
      { name: "Drive to Zero", sector: "Mobilité, énergie, transition", year: "2026", type: "Salon professionnel" },
      { name: "Salon du Fromage et des Produits Laitiers", sector: "Alimentation, produits laitiers", year: "2026", type: "Salon professionnel" },
      { name: "Gourmet Selection", sector: "Alimentation, épicerie fine", year: "2026", type: "Salon professionnel" },
      { name: "MOBCO", sector: "Transport, mobilité, logistique", year: "2026", type: "Salon professionnel" },
      { name: "SMAPIMMO", sector: "Immobilier, investissement", year: "2026", type: "Salon grand public" },
      { name: "Korea Expo", sector: "Commerce, culture internationale", year: "2026", type: "Salon mixte" },
      { name: "Tech For Industry Show", sector: "Industrie, tech, digitalisation", year: "2026", type: "Salon professionnel" },
      { name: "ISTH Congress", sector: "Santé, hématologie", year: "2026", type: "Congrès" },
      { name: "Japan Expo", sector: "Culture, entertainment, licensing", year: "2026", type: "Salon mixte" },
      { name: "Maison & Objet Paris (septembre)", sector: "Design, décoration, habitat premium", year: "2026", type: "Salon professionnel" },
      { name: "Maison & Objet Paris (janvier)", sector: "Design, décoration, habitat premium", year: "2027", type: "Salon professionnel" },
      { name: "NRF Retail's Big Show Europe / Paris Retail Week", sector: "Retail, commerce, expérience client", year: "2026", type: "Salon professionnel" },
      { name: "MCB by Beauté Sélection", sector: "Beauté, coiffure, cosmétique", year: "2026", type: "Salon professionnel" },
      { name: "Mondial de l'Auto", sector: "Automobile, mobilité, industrie", year: "2026", type: "Salon mixte" },
      { name: "EquipHotel", sector: "Hôtellerie, restauration, food service", year: "2026", type: "Salon professionnel" },
      { name: "Paris Nautic Show", sector: "Nautisme, tourisme, sports", year: "2026", type: "Salon grand public" },
      { name: "ALL4PACK Emballage Paris", sector: "Packaging, manutention, logistique", year: "2026", type: "Salon professionnel" },
      { name: "SITL Paris", sector: "Transport, logistique, supply chain", year: "2027", type: "Salon professionnel" },
      { name: "Première Vision Paris", sector: "Mode, textile, luxe", year: "2027", type: "Salon professionnel" },
      { name: "Silmo Paris", sector: "Optique, lunetterie, santé visuelle", year: "2027", type: "Salon professionnel" },
      { name: "Expoprotection", sector: "Sécurité, prévention, risques", year: "2026", type: "Salon professionnel" },
      { name: "Intermat Paris", sector: "Construction, BTP, engins", year: "2027", type: "Salon professionnel" },
      { name: "Interclima", sector: "Bâtiment, énergie, génie climatique", year: "2026", type: "Salon professionnel" },
      { name: "Idéobain", sector: "Bâtiment, salle de bain, habitat", year: "2026", type: "Salon professionnel" },
      { name: "Equipbaie / Metalexpo", sector: "Bâtiment, menuiserie, métal", year: "2026", type: "Salon professionnel" },
      { name: "Mondial du Bâtiment", sector: "Bâtiment, construction, architecture", year: "2026", type: "Salon professionnel" },
      { name: "Salon des Maires et des Collectivités Locales", sector: "Collectivités, institutionnel", year: "2026", type: "Salon professionnel" },
      { name: "SIMI", sector: "Immobilier, tertiaire, investissement", year: "2026", type: "Salon professionnel" },
      { name: "SIEC", sector: "Retail, immobilier commercial", year: "2027", type: "Salon professionnel" },
      { name: "MIF Expo — Made in France", sector: "Industrie, fabrication française", year: "2026", type: "Salon mixte" },
      { name: "Salon du Chocolat Paris", sector: "Alimentation, gastronomie, retail", year: "2026", type: "Salon mixte" },
      { name: "Natexpo Paris", sector: "Bio, alimentation, cosmétique", year: "2027", type: "Salon professionnel" },
      { name: "Food Hotel Tech Paris", sector: "Hôtellerie, restauration, tech", year: "2027", type: "Salon professionnel" },
      { name: "Sandwich & Snack Show", sector: "Food service, snacking, restauration", year: "2027", type: "Salon professionnel" },
      { name: "Parizza", sector: "Food service, restauration italienne", year: "2027", type: "Salon professionnel" },
      { name: "Vending Paris", sector: "Distribution automatique, food service", year: "2027", type: "Salon professionnel" },
      { name: "Europain", sector: "Boulangerie, pâtisserie, food service", year: "2028", type: "Salon professionnel" },
      { name: "Wine Paris & Vinexpo Paris", sector: "Vin, spiritueux, food", year: "2027", type: "Salon professionnel" },
      { name: "Salon International de l'Agriculture", sector: "Agriculture, agroalimentaire", year: "2027", type: "Salon mixte" },
      { name: "Rétromobile", sector: "Automobile, collection, luxe", year: "2027", type: "Salon professionnel et public" },
      { name: "Equip Auto Paris", sector: "Automobile, aftermarket, industrie", year: "2027", type: "Salon professionnel" },
      { name: "Hyvolution Paris", sector: "Hydrogène, énergie, industrie", year: "2027", type: "Salon professionnel" },
      { name: "Autonomy Mobility World Expo", sector: "Mobilité, transport, smart city", year: "2027", type: "Salon professionnel" },
      { name: "ChangeNOW", sector: "Impact, environnement, innovation", year: "2027", type: "Salon professionnel" },
      { name: "Workspace Expo", sector: "Aménagement, bureau, mobilier tertiaire", year: "2027", type: "Salon professionnel" },
      { name: "Heavent Paris", sector: "Événementiel, communication, stand", year: "2026", type: "Salon professionnel" },
      { name: "Salon SME", sector: "Entrepreneuriat, services B2B", year: "2026", type: "Salon professionnel" },
      { name: "Go Entrepreneurs Paris", sector: "Entrepreneuriat, services aux entreprises", year: "2027", type: "Salon professionnel" },
      { name: "Franchise Expo Paris", sector: "Franchise, commerce, retail", year: "2027", type: "Salon professionnel" },
      { name: "Paris Packaging Week", sector: "Packaging, luxe, cosmétique, boisson", year: "2027", type: "Salon professionnel" },
      { name: "MakeUp in Paris", sector: "Cosmétique, beauté, packaging", year: "2027", type: "Salon professionnel" },
      { name: "PharmagoraPlus", sector: "Santé, pharmacie, retail santé", year: "2027", type: "Salon professionnel" },
      { name: "Journées Françaises de Radiologie (JFR)", sector: "Santé, radiologie, imagerie médicale", year: "2026", type: "Congrès" },
      { name: "Congrès ADF", sector: "Santé, dentaire, équipements médicaux", year: "2026", type: "Congrès + exposition" },
      { name: "SFAR — Congrès d'anesthésie-réanimation", sector: "Santé, anesthésie, dispositifs médicaux", year: "2026", type: "Congrès" },
      { name: "JFHOD", sector: "Santé, hépato-gastroentérologie", year: "2027", type: "Congrès" },
      { name: "Congrès de la Société Francophone du Diabète", sector: "Santé, diabète, pharma", year: "2027", type: "Congrès" },
      { name: "Congrès de la Médecine Générale France", sector: "Santé, médecine générale", year: "2027", type: "Congrès" },
      { name: "Journées Dermatologiques de Paris", sector: "Santé, dermatologie, pharma", year: "2026", type: "Congrès" },
      { name: "Congrès Français de Psychiatrie", sector: "Santé, psychiatrie", year: "2026", type: "Congrès" },
      { name: "Paris Healthcare Week", sector: "Santé, systèmes hospitaliers, innovation", year: "2027", type: "Salon professionnel" },
      { name: "Preventica Paris", sector: "Santé sécurité au travail, prévention", year: "2027", type: "Salon professionnel" },
      { name: "Big Data & AI Paris", sector: "Tech, data, intelligence artificielle", year: "2026", type: "Salon professionnel" },
      { name: "Cloud Expo Europe Paris", sector: "Tech, cloud, cybersécurité", year: "2026", type: "Salon professionnel" },
      { name: "Data Centre World Paris", sector: "Tech, data centers, infrastructure", year: "2026", type: "Salon professionnel" },
      { name: "Cybersecurity World Paris", sector: "Cyber, sécurité, IT", year: "2026", type: "Salon professionnel" },
      { name: "SIDO Paris", sector: "IoT, IA, robotique, tech", year: "2026", type: "Salon professionnel" },
      { name: "Tech Show Paris", sector: "Tech, IT, cloud, cyber", year: "2026", type: "Salon professionnel" },
      { name: "AI for Health Summit", sector: "Santé, IA, innovation", year: "2026", type: "Congrès" },
      { name: "Paris Blockchain Week", sector: "Finance, blockchain, tech", year: "2027", type: "Congrès + salon" },
      { name: "Salon de la Photo", sector: "Image, photo, équipement", year: "2026", type: "Salon mixte" },
      { name: "Paris Games Week", sector: "Jeux vidéo, entertainment, tech", year: "2026", type: "Salon grand public" },
      { name: "Paris Manga & Sci-Fi Show", sector: "Pop culture, entertainment, retail", year: "2026", type: "Salon grand public" },
      { name: "Kidexpo", sector: "Famille, jeux, éducation, retail", year: "2026", type: "Salon grand public" },
      { name: "Salon Européen de l'Éducation", sector: "Éducation, formation, institutionnel", year: "2026", type: "Salon professionnel et public" },
      { name: "Educatech Expo", sector: "Éducation, digital learning, tech", year: "2026", type: "Salon professionnel" },
      { name: "Salon de l'Étudiant Paris", sector: "Éducation, orientation, formation", year: "2027", type: "Salon grand public" },
      { name: "Studyrama Grandes Écoles Paris", sector: "Éducation, orientation, formation", year: "2026", type: "Salon grand public" },
      { name: "Salon des Seniors", sector: "Services, santé, lifestyle", year: "2027", type: "Salon mixte" },
      { name: "Salon Bien-être Médecine Douce", sector: "Bien-être, santé, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Salon Zen", sector: "Bien-être, lifestyle, retail", year: "2026", type: "Salon grand public" },
      { name: "Salon Marjolaine", sector: "Bio, bien-être, consommation responsable", year: "2026", type: "Salon grand public" },
      { name: "Créations & savoir-faire", sector: "Créateurs, loisirs créatifs, retail", year: "2026", type: "Salon grand public" },
      { name: "Art Paris", sector: "Art, galeries, luxe, collection", year: "2027", type: "Salon professionnel et public" },
      { name: "Livre Paris / Festival du Livre de Paris", sector: "Édition, culture, communication", year: "2027", type: "Salon mixte" },
      { name: "Paris Audio Video Show", sector: "High-tech, audio, image, retail", year: "2026", type: "Salon mixte" },
      { name: "Texworld Paris", sector: "Textile, mode, sourcing", year: "2027", type: "Salon professionnel" },
      { name: "Apparel Sourcing Paris", sector: "Textile, mode, sourcing", year: "2027", type: "Salon professionnel" },
      { name: "Avantex Paris", sector: "Textile, innovation, mode", year: "2027", type: "Salon professionnel" },
      { name: "Leatherworld Paris", sector: "Cuir, mode, sourcing", year: "2027", type: "Salon professionnel" },
      { name: "Who's Next", sector: "Mode, retail, marques", year: "2027", type: "Salon professionnel" },
      { name: "Première Classe", sector: "Mode, accessoires, premium", year: "2027", type: "Salon professionnel" },
      { name: "Bijorhca Paris", sector: "Bijouterie, mode, retail", year: "2027", type: "Salon professionnel" },
      { name: "Salon International de la Lingerie", sector: "Mode, lingerie, retail", year: "2027", type: "Salon professionnel" },
      { name: "Curve Paris", sector: "Mode, lingerie, swimwear", year: "2027", type: "Salon professionnel" },
      { name: "Première Vision Denim", sector: "Mode, textile, denim", year: "2026", type: "Salon professionnel" },
      { name: "Paris Design Week / Maison & Objet in the City", sector: "Design, décoration, expérience marque", year: "2026", type: "Parcours professionnel" },
      { name: "Forum Labo Paris", sector: "Laboratoire, industrie, recherche", year: "2027", type: "Salon professionnel" },
      { name: "Eurocoat", sector: "Industrie, peinture, chimie, matériaux", year: "2028", type: "Salon professionnel" },
      { name: "Forum International de la Cybersécurité — Paris", sector: "Cyber, sécurité, souveraineté numérique", year: "2027", type: "Congrès + salon" },
      { name: "Paris Space Week", sector: "Spatial, aéronautique, innovation", year: "2027", type: "Salon professionnel" },
      { name: "Rééduca Paris", sector: "Santé, kinésithérapie, matériel médical", year: "2026", type: "Salon professionnel" },
      { name: "Congrès des Sociétés de Pédiatrie", sector: "Santé, pédiatrie, pharma", year: "2026", type: "Congrès" },
      { name: "Congrès Français d'Urologie", sector: "Santé, urologie, dispositifs médicaux", year: "2026", type: "Congrès" },
      { name: "Congrès Français de Rhumatologie", sector: "Santé, rhumatologie, pharma", year: "2026", type: "Congrès" },
    ],
    sectors: [
      "Tech & SaaS",
      "Luxe & cosmétique",
      "Agroalimentaire",
      "Aéronautique & défense",
      "Industrie",
      "Mode & retail",
    ],
    localContext:
      "Notre équipe coordonne les opérations parisiennes en lien direct avec les services techniques de Viparis, GL Events et Comexposium : passage des plans, validation sécurité, montage de nuit, gestion des accès matériel. Notre réseau d'installateurs Île-de-France garantit des montages dans les fenêtres horaires les plus contraintes.",
    cta: "Stand sur-mesure, modulaire, pop-up ou roadshow à Paris ? Discutons de votre prochain salon.",
  },

  lyon: {
    slug: "lyon",
    name: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    title: "Stand & design d'espaces Lyon, Eurexpo, Sirha, Pollutec | Novaus",
    description:
      "Agence de design de stands à Lyon. Conception sur-mesure, modulaire et roadshow pour Eurexpo : Global Industrie, Pollutec, Sirha, Eurobois, Solutrans, Préventica et plus de 50 salons rhônalpins.",
    intro:
      "Lyon est le second pôle d'exposition de France. Eurexpo et le Centre de Congrès accueillent des salons B2B parmi les plus stratégiques du pays, particulièrement dans l'industrie, l'agroalimentaire et l'environnement.",
    hook: "À Lyon, l'industrie ne pardonne pas l'à-peu-près.",
    venues: [
      {
        name: "Eurexpo Lyon",
        desc: "140 000 m² couverts, 7 halls. Global Industrie, Pollutec, Sirha, Eurobois, Solutrans, Piscine Global, Préventica.",
      },
      {
        name: "Lyon — Centre de Congrès",
        desc: "Cité Internationale, 24 000 m². Patrimonia, congrès médicaux et lancements premium.",
      },
      {
        name: "La Sucrière / Halle Tony Garnier",
        desc: "Espaces atypiques pour pop-up, lancements de marque et événements de prestige.",
      },
    ],
    featuredFairs: [
      { name: "Global Industrie Lyon", sector: "Industrie, machines, innovation", year: "2027", venue: "Eurexpo", type: "Salon professionnel" },
      { name: "Pollutec", sector: "Environnement, énergie, industrie", year: "2027", venue: "Eurexpo", type: "Salon professionnel" },
      { name: "Sirha Lyon", sector: "Food service, hôtellerie, restauration", year: "2027", venue: "Eurexpo", type: "Salon professionnel" },
      { name: "Eurobois", sector: "Bois, industrie, construction", year: "2028", venue: "Eurexpo", type: "Salon professionnel" },
      { name: "Solutrans", sector: "Transport, véhicules industriels, logistique", year: "2027", venue: "Eurexpo", type: "Salon professionnel" },
      { name: "Préventica Lyon", sector: "Prévention, sécurité, santé au travail", year: "2026", venue: "Eurexpo", type: "Salon professionnel" },
    ],
    allFairs: [
      { name: "Piscine Global Europe", sector: "Piscine, wellness, équipement", year: "2026", type: "Salon professionnel" },
      { name: "Equita Lyon", sector: "Équestre, sport, lifestyle", year: "2026", type: "Salon mixte" },
      { name: "Epoqu'Auto", sector: "Automobile, collection, lifestyle", year: "2026", type: "Salon mixte" },
      { name: "FIP Solution Plastique", sector: "Industrie plastique, machines", year: "2026", type: "Salon professionnel" },
      { name: "3D Print Lyon", sector: "Industrie, fabrication additive, innovation", year: "2026", type: "Salon professionnel" },
      { name: "Journées COFREND", sector: "Industrie, contrôle non destructif", year: "2026", type: "Congrès + salon" },
      { name: "MSE — Mesures Solutions Expo", sector: "Industrie, mesure, instrumentation", year: "2026", type: "Salon professionnel" },
      { name: "Patrimonia", sector: "Finance, patrimoine, gestion privée", year: "2026", type: "Salon professionnel" },
      { name: "BePositive", sector: "Énergie, bâtiment, transition", year: "2027", type: "Salon professionnel" },
      { name: "Paysalia", sector: "Paysage, végétal, aménagement", year: "2027", type: "Salon professionnel" },
      { name: "Rocalia", sector: "Pierre naturelle, construction, design", year: "2027", type: "Salon professionnel" },
      { name: "Europack Euromanut CFIA", sector: "Packaging, manutention, industrie agro", year: "2027", type: "Salon professionnel" },
      { name: "Natexpo Lyon", sector: "Bio, alimentation, cosmétique", year: "2026", type: "Salon professionnel" },
      { name: "Salon Automobile de Lyon", sector: "Automobile, mobilité", year: "2027", type: "Salon mixte" },
      { name: "Mahana Lyon", sector: "Tourisme, loisirs", year: "2027", type: "Salon grand public" },
      { name: "Mondial des Métiers", sector: "Formation, emploi, orientation", year: "2027", type: "Salon professionnel et public" },
      { name: "Salon de l'Étudiant Lyon", sector: "Éducation, orientation", year: "2027", type: "Salon grand public" },
      { name: "Go Entrepreneurs Lyon", sector: "Entrepreneuriat, services B2B", year: "2027", type: "Salon professionnel" },
      { name: "Thermalies Lyon", sector: "Bien-être, tourisme santé", year: "2027", type: "Salon grand public" },
      { name: "Art3f Lyon", sector: "Art, galeries, collection", year: "2027", type: "Salon mixte" },
      { name: "Japan Touch / Salon de l'Asie Lyon", sector: "Pop culture, retail, entertainment", year: "2026", type: "Salon grand public" },
      { name: "Salon du Chocolat Lyon", sector: "Gastronomie, chocolat, retail", year: "2027", type: "Salon mixte" },
      { name: "ID Créatives Lyon", sector: "Loisirs créatifs, retail", year: "2026", type: "Salon grand public" },
      { name: "Salon Habitat Lyon", sector: "Habitat, décoration, rénovation", year: "2026", type: "Salon grand public" },
      { name: "Naturally / Vivez Nature Lyon", sector: "Bio, bien-être, consommation responsable", year: "2026", type: "Salon grand public" },
      { name: "Salon Primevère", sector: "Écologie, environnement, citoyen", year: "2027", type: "Salon mixte" },
      { name: "Lyon Cyber Expo", sector: "Cyber, numérique, sécurité", year: "2027", type: "Congrès + salon" },
      { name: "Sido Lyon", sector: "IoT, IA, robotique, tech", year: "2026", type: "Salon professionnel" },
      { name: "Mix.E Lyon", sector: "Énergie, industrie, transition", year: "2027", type: "Salon professionnel" },
      { name: "Open Energies Lyon", sector: "Énergie, solaire, smart grids", year: "2027", type: "Salon professionnel" },
      { name: "Congrès SF2H Lyon", sector: "Santé, hygiène hospitalière", year: "2027", type: "Congrès" },
      { name: "Congrès de la Société Française de Cardiologie Lyon", sector: "Santé, cardiologie", year: "2027", type: "Congrès" },
      { name: "Congrès de Pneumologie Lyon", sector: "Santé, pneumologie", year: "2027", type: "Congrès" },
      { name: "Congrès des Notaires de France Lyon", sector: "Juridique, institutionnel, services", year: "2027", type: "Congrès" },
      { name: "Salon des CE / CSE Lyon", sector: "Services aux entreprises, CSE", year: "2027", type: "Salon professionnel" },
      { name: "Forum Franchise Lyon", sector: "Franchise, commerce, retail", year: "2026", type: "Salon professionnel" },
      { name: "Lyon Tasting", sector: "Vin, gastronomie, premium", year: "2026", type: "Salon mixte" },
      { name: "Salon des Vins des Vignerons Indépendants Lyon", sector: "Vin, gastronomie, retail", year: "2026", type: "Salon grand public" },
      { name: "Geek & Touch Lyon", sector: "Pop culture, gaming, retail", year: "2027", type: "Salon grand public" },
      { name: "Lyon Game Show", sector: "Gaming, entertainment, tech", year: "2027", type: "Salon grand public" },
      { name: "Salon du 2 Roues Lyon", sector: "Moto, mobilité, sport", year: "2027", type: "Salon mixte" },
      { name: "Sirha Omnivore Lyon", sector: "Food, restauration, chefs", year: "2027", type: "Salon professionnel" },
      { name: "Sirha Bake & Snack", sector: "Food service, boulangerie, snacking", year: "2028", type: "Salon professionnel" },
      { name: "Rendez-vous Carnot Lyon", sector: "Innovation, R&D, industrie", year: "2026", type: "Congrès + salon" },
      { name: "Industrie Time Lyon", sector: "Industrie, production, équipements", year: "2027", type: "Salon professionnel" },
      { name: "Salon Solutions RH Lyon", sector: "RH, formation, digital workplace", year: "2027", type: "Salon professionnel" },
      { name: "Meet & Com Lyon", sector: "Communication, événementiel, MICE", year: "2027", type: "Salon professionnel" },
      { name: "Congrès HLM Lyon", sector: "Logement social, institutionnel, construction", year: "2027", type: "Congrès + salon" },
      { name: "Salon de la Copropriété Lyon", sector: "Immobilier, habitat, services", year: "2027", type: "Salon professionnel" },
      { name: "Bio360 Expo Lyon", sector: "Bioénergie, environnement, industrie", year: "2027", type: "Salon professionnel" },
    ],
    sectors: [
      "Industrie & manufacturing",
      "Énergie & environnement",
      "Agroalimentaire & restauration",
      "Santé & pharmaceutique",
      "Transport & logistique",
      "Bâtiment & construction",
    ],
    localContext:
      "Notre logistique inclut un sourcing local de prestataires lyonnais (impression grand format, mobilier, fleurs et aménagement végétal), une coordination directe avec GL Events Eurexpo, et un suivi de montage sur site. Pour les exposants nationaux, nous gérons le transport stockage Île-de-France ↔ Lyon en flux tendu.",
    cta: "Sirha, Pollutec, Global Industrie ? Briefons votre prochain stand lyonnais.",
  },

  cannes: {
    slug: "cannes",
    name: "Cannes",
    region: "Provence-Alpes-Côte d'Azur",
    title: "Stand sur-mesure Cannes, MIPIM, TFWA, MAPIC, Palais des Festivals | Novaus",
    description:
      "Agence de design de stands à Cannes. Conception premium pour le Palais des Festivals : MIPIM, TFWA, MAPIC, ILTM, Cannes Yachting Festival, World AI Cannes et plus de 40 événements internationaux.",
    intro:
      "Cannes est la scène internationale du luxe, de l'immobilier d'investissement et des médias. Le Palais des Festivals concentre des salons de niveau mondial où la qualité de l'écrin compte autant que celle de la marque.",
    hook: "À Cannes, le détail signe la marque. Rien ne doit jurer.",
    venues: [
      {
        name: "Palais des Festivals et des Congrès",
        desc: "35 000 m². MIPIM, TFWA World Exhibition, MAPIC, ILTM, MIPCOM, Cannes Lions, Festival International des Jeux.",
      },
      {
        name: "Plages & Pavillons partenaires",
        desc: "Activations de marques, lancements et hospitality lors du Festival de Cannes et des Cannes Lions.",
      },
      {
        name: "Hôtels Croisette (Carlton, Majestic, Martinez)",
        desc: "Lounges, suites éphémères et espaces VIP pour brand experiences premium.",
      },
    ],
    featuredFairs: [
      { name: "MIPIM", sector: "Immobilier, investissement, collectivités", year: "2027", venue: "Palais des Festivals", type: "Salon professionnel" },
      { name: "TFWA World Exhibition & Conference", sector: "Travel retail, luxe, duty free", year: "2026", venue: "Palais des Festivals", type: "Salon professionnel" },
      { name: "MAPIC", sector: "Retail, immobilier commercial", year: "2026", venue: "Palais des Festivals", type: "Salon professionnel" },
      { name: "ILTM Cannes", sector: "Luxe, tourisme, hospitality", year: "2026", venue: "Palais des Festivals", type: "Salon professionnel" },
      { name: "Cannes Yachting Festival", sector: "Nautisme, luxe, tourisme", year: "2026", venue: "Vieux Port & Port Canto", type: "Salon mixte" },
      { name: "World AI Cannes Festival", sector: "IA, technologie, innovation", year: "2027", venue: "Palais des Festivals", type: "Festival professionnel" },
    ],
    allFairs: [
      { name: "Cannes Lions", sector: "Communication, publicité, créativité", year: "2026", type: "Festival professionnel" },
      { name: "MIPCOM", sector: "Audiovisuel, contenus, médias", year: "2026", type: "Salon professionnel" },
      { name: "Festival de Cannes — Marché du Film", sector: "Cinéma, audiovisuel, contenus", year: "2027", type: "Festival + marché professionnel" },
      { name: "Festival International des Jeux", sector: "Jeux, entertainment, retail", year: "2027", type: "Salon mixte" },
      { name: "Canneseries", sector: "Audiovisuel, séries, médias", year: "2027", type: "Festival professionnel" },
      { name: "MIPJunior", sector: "Audiovisuel jeunesse, contenus", year: "2026", type: "Salon professionnel" },
      { name: "MIPTV", sector: "Audiovisuel, contenus, médias", year: "2027", type: "Salon professionnel" },
      { name: "Heavent Meetings", sector: "Événementiel, communication, MICE", year: "2027", type: "Salon professionnel" },
      { name: "IT & Cybersecurity Meetings", sector: "IT, cyber, numérique", year: "2027", type: "Salon professionnel" },
      { name: "Customer Relationship & Marketing Meetings", sector: "Marketing, relation client, retail", year: "2027", type: "Salon professionnel" },
      { name: "Workplace Meetings", sector: "Immobilier tertiaire, services, workplace", year: "2027", type: "Salon professionnel" },
      { name: "Security & Safety Meetings", sector: "Sécurité, sûreté, prévention", year: "2027", type: "Salon professionnel" },
      { name: "Healthcare Meetings", sector: "Santé, innovation, dispositifs médicaux", year: "2027", type: "Salon professionnel" },
      { name: "Hotel & Restaurant Meetings", sector: "Hôtellerie, restauration, hospitality", year: "2027", type: "Salon professionnel" },
      { name: "All4Customer Meetings", sector: "Relation client, marketing, retail tech", year: "2027", type: "Salon professionnel" },
      { name: "Ready For IT", sector: "IT, cloud, cybersécurité", year: "2027", type: "Salon professionnel" },
      { name: "IPEM Cannes", sector: "Finance, private equity, investissement", year: "2027", type: "Salon professionnel" },
      { name: "Luxury Travel Market Cannes", sector: "Luxe, tourisme, hospitality", year: "2027", type: "Salon professionnel" },
      { name: "Cannes Corporate Media & TV Awards", sector: "Communication, corporate, audiovisuel", year: "2027", type: "Congrès / festival" },
      { name: "Tax Free World Exhibition", sector: "Travel retail, luxe, marques internationales", year: "2027", type: "Salon professionnel" },
      { name: "Premium Sourcing Cannes", sector: "Marketing, objet média, cadeaux", year: "2027", type: "Salon professionnel" },
      { name: "Cannes Destination Luxe Forum", sector: "Luxe, hospitalité, marque premium", year: "2027", type: "Forum professionnel" },
      { name: "Cannes Boat & Luxury Experience", sector: "Luxe, nautisme, design", year: "2027", type: "Salon professionnel et public" },
      { name: "Cannes Real Estate Forum", sector: "Immobilier, investissement", year: "2027", type: "Forum professionnel" },
      { name: "Cannes Brands & Entertainment Summit", sector: "Marques, entertainment, communication", year: "2027", type: "Congrès professionnel" },
      { name: "Cannes Retail & Property Meetings", sector: "Retail, immobilier, expérience client", year: "2027", type: "Salon professionnel" },
      { name: "Cannes Hospitality Meetings", sector: "Hospitality, hôtellerie, restauration", year: "2027", type: "Salon professionnel" },
      { name: "Cannes Luxury Packaging Forum", sector: "Packaging, luxe, cosmétique", year: "2027", type: "Forum professionnel" },
      { name: "Cannes Digital Marketing Summit", sector: "Marketing digital, relation client", year: "2027", type: "Congrès professionnel" },
    ],
    sectors: [
      "Luxe & cosmétique",
      "Immobilier international",
      "Médias & audiovisuel",
      "Hospitality & tourisme premium",
      "Yachting & nautisme",
      "Retail & travel retail",
    ],
    localContext:
      "Cannes impose une logistique millimétrée : créneaux de montage très courts, contraintes piétonnes sur la Croisette, douanes pour les exposants internationaux. Notre équipe gère l'acheminement depuis l'Île-de-France ou l'international, le stockage en zone Côte d'Azur, et la coordination avec les services techniques du Palais des Festivals. Pour les opérations sur plages et hôtels, sourcing partenaires PACA (mobilier, fleur, scénographie).",
    cta: "MIPIM, TFWA, MAPIC ? Concevons votre stand cannois à hauteur des standards internationaux.",
  },

  marseille: {
    slug: "marseille",
    name: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    title: "Stand sur-mesure Marseille, Parc Chanot, Palais du Pharo | Novaus",
    description:
      "Agence de design d'espaces à Marseille : stands, showrooms, pop-up et événements pour le Parc Chanot, le Palais du Pharo et les salons régionaux PACA — Foire Internationale, SMIC, Top Transport, Med'Agri, Salon Nautique.",
    intro:
      "Porte d'entrée méditerranéenne de la France, Marseille concentre des salons régionaux à fort rayonnement et des événements maritimes uniques. Le Parc Chanot et le Palais du Pharo sont des écrins exigeants pour les marques qui veulent rayonner sur le sud et le bassin Méditerranée.",
    hook: "À Marseille, le sud impose son tempo. Votre stand doit suivre.",
    venues: [
      {
        name: "Parc Chanot",
        desc: "70 000 m². Foire Internationale de Marseille, SMIC, Top Transport Europe, Salon des Maires PACA, Salon Studyrama.",
      },
      {
        name: "Palais du Pharo",
        desc: "Conventions corporate, congrès médicaux et scientifiques, lancements régionaux face au Vieux-Port.",
      },
      {
        name: "Vieux Port & MUCEM / J1",
        desc: "Espaces atypiques pour Salon Nautique, brand activations et expositions de prestige.",
      },
    ],
    featuredFairs: [
      { name: "Foire Internationale de Marseille", sector: "Habitat, consommation, territoire", year: "2026", venue: "Parc Chanot", type: "Foire" },
      { name: "SMIC — Salon Méditerranéen de l'Immobilier", sector: "Immobilier, investissement", year: "2026", venue: "Parc Chanot", type: "Salon professionnel" },
      { name: "Top Transport Europe", sector: "Logistique & supply chain", year: "2027", venue: "Parc Chanot", type: "Salon professionnel" },
      { name: "Salon Nautique de Marseille", sector: "Plaisance, maritime, lifestyle", year: "2026", venue: "Vieux Port", type: "Salon mixte" },
      { name: "Med'Agri", sector: "Agriculture, agroalimentaire méditerranéen", year: "2026", venue: "Avignon — PACA", type: "Salon professionnel" },
      { name: "Salon des Maires PACA", sector: "Collectivités, institutionnel", year: "2026", venue: "Parc Chanot", type: "Salon professionnel" },
    ],
    allFairs: [
      { name: "Riviera Yachting Network", sector: "Yachting professionnel", year: "2026", type: "Salon professionnel" },
      { name: "Sirha Provence", sector: "Hôtellerie, restauration, food service", year: "2027", type: "Salon professionnel" },
      { name: "Salon de l'Étudiant Marseille", sector: "Éducation, orientation", year: "2027", type: "Salon grand public" },
      { name: "Sup'Alternance Marseille", sector: "Éducation, alternance, RH", year: "2027", type: "Salon grand public" },
      { name: "Salon du Mariage Marseille", sector: "Mariage, événementiel, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Salon de l'Habitat Marseille", sector: "Habitat, décoration, rénovation", year: "2026", type: "Salon grand public" },
      { name: "Salon des Vins des Vignerons Indépendants Marseille", sector: "Vin, gastronomie, retail", year: "2026", type: "Salon grand public" },
      { name: "Studyrama Grandes Écoles Marseille", sector: "Éducation, formation", year: "2027", type: "Salon grand public" },
      { name: "Forum Économique Méditerranéen", sector: "Économie, institutionnel, territoire", year: "2027", type: "Forum professionnel" },
      { name: "Marseille Innovation Healthcare", sector: "Santé, biotech, dispositifs médicaux", year: "2027", type: "Forum professionnel" },
      { name: "Congrès médical Palais du Pharo", sector: "Santé, congrès médical", year: "2027", type: "Congrès" },
      { name: "Salon CSE Marseille", sector: "Services aux entreprises, CSE", year: "2027", type: "Salon professionnel" },
      { name: "Préventica Méditerranée", sector: "Prévention, sécurité, santé au travail", year: "2027", type: "Salon professionnel" },
      { name: "Forum International de la Cybersécurité — Marseille", sector: "Cyber, sécurité, souveraineté numérique", year: "2027", type: "Congrès + salon" },
      { name: "Salon de l'Immobilier Marseille", sector: "Immobilier, habitat, investissement", year: "2027", type: "Salon grand public" },
      { name: "Salon Bio & Bien-être Provence", sector: "Bio, bien-être, consommation responsable", year: "2027", type: "Salon grand public" },
      { name: "Marseille Tattoo Convention", sector: "Lifestyle, création, retail", year: "2027", type: "Salon grand public" },
      { name: "Salon du Chocolat Marseille", sector: "Gastronomie, chocolat, retail", year: "2027", type: "Salon grand public" },
      { name: "Sea Tech Week — extension PACA", sector: "Maritime, tech, innovation", year: "2027", type: "Salon professionnel" },
      { name: "Salon Méditerranéen du Tourisme", sector: "Tourisme, loisirs, territoire", year: "2027", type: "Salon mixte" },
    ],
    sectors: [
      "Maritime & yachting",
      "Logistique & transport",
      "Immobilier & construction",
      "Tourisme & hôtellerie",
      "Cosmétique & parfumerie",
      "Vins & spiritueux",
    ],
    localContext:
      "Marseille demande une logistique pensée pour les contraintes du Vieux-Port et du tunnel Prado-Carénage. Notre équipe coordonne montage de nuit, accès poids lourds et stockage local. Sourcing partenaires PACA (mobilier, fleuriste, traiteur) pour réduire l'empreinte carbone et les délais.",
    cta: "Salon, lancement, pop-up à Marseille ? Concevons un espace à la hauteur du sud.",
  },

  rennes: {
    slug: "rennes",
    name: "Rennes",
    region: "Bretagne",
    title: "Stand sur-mesure Rennes, SPACE, CFIA, ARTIBAT, Parc Expo | Novaus",
    description:
      "Agence de design d'espaces à Rennes : stands sur-mesure, modulaires et pop-up pour le Parc Expo Rennes Aéroport. SPACE, CFIA Rennes, ARTIBAT, Préventica Grand Ouest, Industrie Grand Ouest.",
    intro:
      "Rennes est la capitale agricole et agroalimentaire de l'Ouest. Le Parc Expo Rennes Aéroport accueille des salons de référence — SPACE, CFIA — qui concentrent les filières élevage, productions végétales et IAA. Une scène stratégique pour qui vise le marché ouest-européen.",
    hook: "À Rennes, on parle aux décideurs filière, pas aux curieux.",
    venues: [
      {
        name: "Parc Expo Rennes Aéroport",
        desc: "60 000 m². SPACE, CFIA Rennes, ARTIBAT, Foire Internationale de Rennes, Préventica Grand Ouest.",
      },
      {
        name: "Le Couvent des Jacobins",
        desc: "Centre des congrès de Rennes Métropole, conventions corporate et lancements régionaux.",
      },
      {
        name: "Les Champs Libres",
        desc: "Espace culturel et événementiel atypique pour pop-up et activations de marque.",
      },
    ],
    featuredFairs: [
      { name: "SPACE", sector: "Agriculture, élevage, agroalimentaire", year: "2026", venue: "Rennes Parc Expo", type: "Salon professionnel" },
      { name: "CFIA Rennes", sector: "Agroalimentaire, process, packaging", year: "2027", venue: "Rennes Parc Expo", type: "Salon professionnel" },
      { name: "ARTIBAT", sector: "Bâtiment, construction, artisanat", year: "2027", venue: "Rennes Parc Expo", type: "Salon professionnel" },
      { name: "Préventica Grand Ouest", sector: "Prévention, santé sécurité au travail", year: "2026", venue: "Rennes Parc Expo", type: "Salon professionnel" },
      { name: "Industrie Grand Ouest Rennes", sector: "Industrie, sous-traitance, équipements", year: "2027", venue: "Rennes Parc Expo", type: "Salon professionnel" },
      { name: "Breizh Transition", sector: "Environnement, transition, collectivités", year: "2027", venue: "Rennes Parc Expo", type: "Salon professionnel" },
    ],
    allFairs: [
      { name: "Foire Internationale de Rennes", sector: "Habitat, consommation, territoire", year: "2027", type: "Foire" },
      { name: "Esprit Maison & Jardin Rennes", sector: "Habitat, décoration, jardin", year: "2026", type: "Salon grand public" },
      { name: "Salon La Vie à 2 Rennes", sector: "Mariage, événementiel, lifestyle", year: "2026", type: "Salon grand public" },
      { name: "Viving Rennes", sector: "Habitat, immobilier, rénovation", year: "2027", type: "Salon grand public" },
      { name: "Salon de l'Étudiant Rennes", sector: "Éducation, orientation", year: "2027", type: "Salon grand public" },
      { name: "Sup'Alternance Rennes", sector: "Éducation, alternance, RH", year: "2027", type: "Salon grand public" },
      { name: "Salon du Chocolat Rennes", sector: "Gastronomie, chocolat, retail", year: "2027", type: "Salon grand public" },
      { name: "Salon du Mariage Rennes", sector: "Mariage, événementiel, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Digital Tech Conference Rennes", sector: "Tech, numérique, innovation", year: "2027", type: "Congrès professionnel" },
      { name: "Carrefour des Gestions Locales de l'Eau", sector: "Eau, collectivités, environnement", year: "2027", type: "Salon professionnel" },
      { name: "Forum Économique Breton", sector: "Institutionnel, économie, territoire", year: "2027", type: "Forum professionnel" },
      { name: "Salon des Entrepreneurs Rennes", sector: "Entrepreneuriat, services B2B", year: "2027", type: "Salon professionnel" },
      { name: "Salon CSE Rennes", sector: "Services aux entreprises, CSE", year: "2027", type: "Salon professionnel" },
      { name: "Rennes Games & Pop Culture", sector: "Entertainment, gaming, retail", year: "2027", type: "Salon grand public" },
      { name: "Rennes Tattoo Convention", sector: "Lifestyle, création, retail", year: "2027", type: "Salon grand public" },
      { name: "Salon des Vins des Vignerons Indépendants Rennes", sector: "Vin, gastronomie, retail", year: "2027", type: "Salon grand public" },
      { name: "Rennes Bio & Bien-être", sector: "Bio, bien-être, consommation responsable", year: "2027", type: "Salon grand public" },
      { name: "Rennes Auto Moto Retro", sector: "Automobile, collection, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Salon de l'Immobilier Rennes", sector: "Immobilier, habitat, investissement", year: "2027", type: "Salon grand public" },
      { name: "Rennes Mobilité Durable", sector: "Mobilité, transport, transition", year: "2027", type: "Salon professionnel" },
      { name: "Congrès national vétérinaire Rennes", sector: "Santé animale, élevage, agro", year: "2027", type: "Congrès" },
      { name: "Salon Hôtellerie Restauration Grand Ouest", sector: "Hôtellerie, restauration, food service", year: "2027", type: "Salon professionnel" },
      { name: "Rennes Cyber & Data Forum", sector: "Cyber, data, numérique", year: "2027", type: "Forum professionnel" },
      { name: "Rennes Packaging Agro Forum", sector: "Packaging, agroalimentaire, industrie", year: "2027", type: "Forum professionnel" },
    ],
    sectors: [
      "Agroalimentaire & IAA",
      "Élevage & productions animales",
      "Numérique & cyber",
      "Biotech & santé",
      "Habitat & construction",
      "Formation & enseignement",
    ],
    localContext:
      "Notre couverture du Grand Ouest s'appuie sur un réseau de partenaires bretons et nantais. Nous gérons le transport Paris–Rennes, le stockage local entre deux salons, et le montage en lien direct avec les équipes du Parc Expo Rennes Aéroport. Pour SPACE, l'anticipation logistique est critique : les créneaux de montage sont serrés.",
    cta: "SPACE, CFIA Rennes, ARTIBAT ? Pensons votre stand ouest-français.",
  },

  lille: {
    slug: "lille",
    name: "Lille",
    region: "Hauts-de-France",
    title: "Stand & design d'espaces Lille, Lille Grand Palais, SIFER, NutrEvent | Novaus",
    description:
      "Agence de design de stands à Lille : conception sur-mesure, modulaire et événementielle pour Lille Grand Palais. SIFER, NutrEvent, Autonomic, Nordbat, Congrès Pneumologie, Forum Cybersécurité.",
    intro:
      "Lille est le carrefour économique du nord de l'Europe. À 1 h de Paris, 35 min de Bruxelles, 1 h 20 de Londres, la ville est devenue un hub stratégique pour les salons B2B agroalimentaires, ferroviaires, médicaux et cyber.",
    hook: "À Lille, l'efficacité prime. Votre stand doit transformer en quelques pas.",
    venues: [
      {
        name: "Lille Grand Palais",
        desc: "20 000 m² au cœur de la ville. SIFER, NutrEvent, Autonomic Lille Europe, Nordbat, Congrès médicaux, Salon des Maires HDF.",
      },
      {
        name: "Lille Eurexpo (Tourcoing)",
        desc: "Espace modulable pour conventions, salons techniques et événements régionaux.",
      },
      {
        name: "La Gare Saint-Sauveur / Le Tripostal",
        desc: "Lieux atypiques pour pop-up, brand activation et événements créatifs.",
      },
    ],
    featuredFairs: [
      { name: "SIFER", sector: "Ferroviaire, transport, industrie", year: "2027", venue: "Lille Grand Palais", type: "Salon professionnel" },
      { name: "NutrEvent", sector: "Nutrition, santé, agroalimentaire", year: "2026", venue: "Lille Grand Palais", type: "Salon + conférences" },
      { name: "Autonomic Lille Europe", sector: "Santé, autonomie, accessibilité", year: "2026", venue: "Lille Grand Palais", type: "Salon professionnel" },
      { name: "Nordbat", sector: "Construction, bâtiment, rénovation", year: "2026", venue: "Lille Grand Palais", type: "Salon professionnel" },
      { name: "Congrès de Pneumologie de Langue Française", sector: "Santé, pneumologie, pharma", year: "2027", venue: "Lille Grand Palais", type: "Congrès + exposition" },
      { name: "Forum International de la Cybersécurité Lille", sector: "Cyber, sécurité, souveraineté numérique", year: "2027", venue: "Lille Grand Palais", type: "Congrès + salon" },
    ],
    allFairs: [
      { name: "Salon du Tourisme / Tourissima Lille", sector: "Tourisme, loisirs, territoire", year: "2027", type: "Salon grand public" },
      { name: "Geek Days Lille", sector: "Pop culture, gaming, retail", year: "2026", type: "Salon grand public" },
      { name: "Journées scientifiques RFMF", sector: "Science, métabolomique, recherche", year: "2026", type: "Congrès" },
      { name: "JFICV Lille", sector: "Santé, médecine vasculaire", year: "2026", type: "Congrès" },
      { name: "Congrès AFTES", sector: "BTP, tunnels, infrastructure", year: "2026", type: "Congrès + salon" },
      { name: "AFVAC Le Congrès", sector: "Santé animale, vétérinaire", year: "2026", type: "Congrès + exposition" },
      { name: "Art Up! Lille", sector: "Art contemporain, galeries, collection", year: "2027", type: "Salon mixte" },
      { name: "Salon Créer Lille", sector: "Entrepreneuriat, B2B, services", year: "2027", type: "Salon professionnel" },
      { name: "Amenago Lille", sector: "Habitat, décoration, rénovation", year: "2026", type: "Salon grand public" },
      { name: "Envies Culinaires Lille", sector: "Gastronomie, food, retail", year: "2026", type: "Salon grand public" },
      { name: "Salon du Chocolat Lille", sector: "Gastronomie, chocolat, retail", year: "2027", type: "Salon grand public" },
      { name: "Salon du Mariage Lille", sector: "Mariage, événementiel, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Salon de l'Étudiant Lille", sector: "Éducation, orientation", year: "2027", type: "Salon grand public" },
      { name: "Sup'Alternance Lille", sector: "Éducation, alternance, RH", year: "2027", type: "Salon grand public" },
      { name: "Salon CSE Lille", sector: "Services aux entreprises, CSE", year: "2027", type: "Salon professionnel" },
      { name: "Age 3 / Handicap Lille", sector: "Santé, autonomie, médico-social", year: "2027", type: "Salon professionnel" },
      { name: "Made in Hainaut / Nord Industrie", sector: "Industrie, territoire, sous-traitance", year: "2027", type: "Salon professionnel" },
      { name: "Business Power Lille", sector: "Business, réseau, entrepreneuriat", year: "2027", type: "Salon professionnel" },
      { name: "Salon Immobilier Lille", sector: "Immobilier, habitat, investissement", year: "2027", type: "Salon grand public" },
      { name: "Lille Bio & Bien-être", sector: "Bio, bien-être, consommation responsable", year: "2027", type: "Salon grand public" },
      { name: "Lille Tattoo Convention", sector: "Lifestyle, création, retail", year: "2027", type: "Salon grand public" },
      { name: "Lille Auto Retro", sector: "Automobile, collection, lifestyle", year: "2027", type: "Salon grand public" },
      { name: "Santé Innovation Lille", sector: "Santé, medtech, nutrition", year: "2027", type: "Forum professionnel" },
      { name: "Lille Retail Forum", sector: "Retail, commerce, expérience client", year: "2027", type: "Forum professionnel" },
      { name: "Lille Packaging & Supply Forum", sector: "Packaging, supply chain, industrie", year: "2027", type: "Forum professionnel" },
      { name: "Lille Industrie & Maintenance", sector: "Industrie, maintenance, équipements", year: "2027", type: "Salon professionnel" },
      { name: "Lille Habitat & Jardin", sector: "Habitat, jardin, rénovation", year: "2027", type: "Salon grand public" },
      { name: "Lille Food & Hospitality", sector: "Hôtellerie, restauration, food service", year: "2027", type: "Salon professionnel" },
      { name: "Lille Data & IA Forum", sector: "Data, IA, numérique", year: "2027", type: "Forum professionnel" },
      { name: "Congrès médical Lille Grand Palais", sector: "Santé, congrès médical", year: "2027", type: "Congrès" },
    ],
    sectors: [
      "Agroalimentaire & IAA",
      "Ferroviaire & transport",
      "Logistique & e-commerce",
      "Biotech & santé",
      "Distribution & retail",
      "Cyber & numérique",
    ],
    localContext:
      "Lille bénéficie d'un tissu d'installateurs et de fabricants nordistes très réactifs. Nous travaillons avec des partenaires locaux pour optimiser les délais de montage, réduire les transports et garantir une production éco-responsable. Coordination directe avec les équipes de Lille Grand Palais.",
    cta: "SIFER, NutrEvent, Forum Cybersécurité ? Construisons votre présence lilloise.",
  },
};
